#theme: jekyll-theme-cayman
remote_theme             : "mmistakes/minimal-mistakes@4.15.1"
layout: home
tagline: hola
title: fr3d1s4nm4r

#site author
author:
  name: "fr3d1s4nm4r"
  location: "Madrid"
  email: "fr3d1s4nm4r@gmail.com"

#conversions
markdown: kramdown




#-----rss share------#
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false





#------colors--------#
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"